# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f8baa2cacf6cfff4ac6780ff48bf52b"
name = "LoyaltyPulse"
application_url = "https://legroom-perkiness-bucktooth.ngrok-free.dev"
embedded = true
handle = "loyaltypulse-suraj-2026"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/api/webhooks/compliance"

[access_scopes]
# Minimal scopes for loyalty: orders webhooks, discount creation, app proxy
scopes = "read_orders,read_customers,write_discounts,write_app_proxy"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://legroom-perkiness-bucktooth.ngrok-free.dev/auth/callback"
]

[app_proxy]
url = "https://legroom-perkiness-bucktooth.ngrok-free.dev/apps/loyaltypulse"
subpath = "loyaltypulse"
prefix = "apps"
